config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'
  resources :comments
  resources :topics do
    resources :comments
  end
  get "/topics/:topic_id/comments/:comment_id/comments/new" => "comments#new"
end

app/models/comment.rb
require 'autoinc'
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Autoinc

  field :number, type: Integer
  increments :number
  field :text, type: String
  field :topic_id, type: String
  field :comment_id, type: String

  belongs_to :topic, class_name: "Topic"
  belongs_to :comment, class_name: "Comment"
  has_many :comments, class_name: "Comment", foreign_key: "comment_id"

  validates_presence_of :text

  before_destroy :check_for_children

  PER_PAGE = 5

  def is_first_level?
    self.comment.nil?
  end

  def get_topic
    self.is_first_level? ? self.topic : self.comment.get_topic
  end

  private
  def check_for_children
    unless self.comments.nil? || self.comments.empty?
      self.errors[:base] << "Cannot delete comment while its children exists."
      return false
    end
  end

end

app/models/topic.rb
require 'autoinc'
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Autoinc

  field :number, type: Integer
  increments :number
  field :text, type: String

  has_many :comments

  validates_presence_of :text

  before_destroy :check_for_children

  PER_PAGE = 5

  private
  def check_for_children
    unless self.comments.nil? || self.comments.empty?
      self.errors[:base] << "Cannot delete topic while its children exists."
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = params[:topic_id] ? Comment.where(topic_id: params[:topic_id]) : Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    @comment.topic = Topic.find(params[:topic_id])
    @comment.comment = Comment.find(params[:comment_id]) if params[:comment_id]
    @comment
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.topic, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.topic }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.topic, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment.topic }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    respond_to do |format|
      if @comment.destroy
        format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :show }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:text, :topic_id, :comment_id)
    end
end

app/controllers/topics_controller.rb
require 'will_paginate_mongoid'
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.order_by(:number => 'asc').paginate(:page => params[:page], :per_page => Topic::PER_PAGE)
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    respond_to do |format|
      if @topic.destroy
        format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :show }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
    set_comments
  end

  def set_comments
    @topic.comments = @topic.comments.where(comment: nil, topic: @topic.id)
    @comments = @topic.comments.paginate(:page => params[:page], :per_page => Comment::PER_PAGE)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:_id, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper

  def get_html_nested_comments(topic_number, comments)
    html = "<ul style='list-style-type:none'>"
    comments.each_with_index do |c, i|
      index = (c.is_first_level?) ? get_index_by_page + (i + 1) : (i + 1)
      index = "#{topic_number}.#{index}"
      html +="  <li><strong>#{index}</strong>
                  #{c.created_at} #{SimpleBlacklist.sanitize c.text}
                  <a href='/topics/#{c.get_topic.id}/comments/#{c.id}/comments/new' class='btn btn-default btn-xs'>Reply</a>"
      html +=" #{get_html_nested_comments("#{index}", c.comments)}" unless c.comments.empty?
      html +="</li>"
    end
    html += "</ul>"
    html
  end

  def get_index_by_page
    page = (params[:page].to_i < 2) ? 1 : params[:page].to_i
    ((page - 1) * Comment::PER_PAGE)
  end
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <input type="hidden" name="comment[topic_id]" id="comment_topic_id" value="<%= @comment.topic.id %>">
  <% if @comment.comment %>
    <input type="hidden" name="comment[comment_id]" id="comment_comment_id" value="<%= @comment.comment.id %>">
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <button type="submit" class="btn btn-default"><i class='glyphicon glyphicon-floppy-disk'></i> Save</button>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="row-fluid">
  <%= link_to raw('<i class="glyphicon glyphicon-circle-arrow-left"></i> Back'), comments_path, class: "btn btn-default" %>
  <%= link_to raw('<i class="glyphicon glyphicon-eye-open"></i> Show'), @comment, class: "btn btn-default" %>
</div>

<h1>Editing Comment</h1>
<%= render 'form' %>

app/views/comments/index.html.erb
<div class="row-fluid">
  <%= link_to raw('<i class="glyphicon glyphicon-plus"></i> New Comment'), new_comment_path, class: "btn btn-default" %>
</div>

<h1>Listing Comments</h1>
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Text</th>
      <th>Topic</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.text %></td>
        <td><%= comment.topic_id %></td>
        <td><%= comment.comment_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/new.html.erb
<div class="row-fluid">
  <%= link_to raw('<i class="glyphicon glyphicon-circle-arrow-left"></i> Back'), @comment.get_topic, class: "btn btn-default" %>
</div>

<h1>New Comment</h1>
<%= render 'form' %>

app/views/comments/show.html.erb
<div class="row-fluid">
  <%= link_to raw('<i class="glyphicon glyphicon-circle-arrow-left"></i> Back'), comments_path, class: "btn btn-default" %>
  <%= link_to raw('<i class="glyphicon glyphicon-pencil"></i> Edit'), edit_comment_path(@comment), class: "btn btn-default" %>
  <%= link_to raw('<i class="glyphicon glyphicon-trash"></i> Destroy'), @comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
</div>

<% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @comment.topic_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment_id %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "R7Forum" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="row">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">R7Forum</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Topics", "/topics"  %></li>
          </ul>
        </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <footer>
      <p>&copy; Company 2016</p>
    </footer>
  </div><!--/row-->
</div> <!-- /container -->

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

        <ul>
          <% @topic.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <button type="submit" class="btn btn-default"><i class='glyphicon glyphicon-floppy-disk'></i> Save</button>
  </div>
<% end %>

app/views/topics/edit.html.erb
<div class="row-fluid">
  <%= link_to raw('<i class="glyphicon glyphicon-circle-arrow-left"></i> Back'), topics_path, class: "btn btn-default" %>
  <%= link_to raw('<i class="glyphicon glyphicon-eye-open"></i> Show'), @topic, class: "btn btn-default" %>
</div>

<h1>Editing Topic</h1>
<%= render 'form' %>

app/views/topics/index.html.erb
<div class="row-fluid">
  <%= link_to raw('<i class="glyphicon glyphicon-plus"></i> New Topic'), new_topic_path, class: "btn btn-default" %>
</div>

<h1>Listing Topics</h1>
<div class="row-fluid">
    <ul class="list-unstyled">
      <% @topics.each do |topic| %>
          <li style="margin: 3px 0 3px 0">
            <strong><%= topic.number %>.</strong>
            <a href="/topics/<%= topic.id %>"><%= topic.created_at %></a> <%= SimpleBlacklist.sanitize topic.text %>
          </li>
      <% end %>
    </ul>
</div>

<div class="row-fluid">
  <%= will_paginate @topics, renderer: BootstrapPagination::Rails %>
</div>

app/views/topics/new.html.erb
<div class="row-fluid">
  <%= link_to raw('<i class="glyphicon glyphicon-circle-arrow-left"></i> Back'), topics_path, class: "btn btn-default" %>
</div>

<h1>New Topic</h1>
<%= render 'form' %>

app/views/topics/show.html.erb
<div class="row-fluid">
  <%= link_to raw('<i class="glyphicon glyphicon-circle-arrow-left"></i> Back'), topics_path, class: "btn btn-default" %>
  <%= link_to raw('<i class="glyphicon glyphicon-pencil"></i> Edit'), edit_topic_path(@topic), class: "btn btn-default" %>
  <%= link_to raw('<i class="glyphicon glyphicon-trash"></i> Destroy'), @topic, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
</div>

<% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @topic.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="row-fluid">
  <ul class="list-unstyled">
    <li>
      <strong><%= @topic.number %>.</strong>
      <%= @topic.created_at %> <%= SimpleBlacklist.sanitize @topic.text %>
      <a href="/topics/<%= @topic.id %>/comments/new" class="btn btn-default btn-xs">Reply</a>

      <% if @comments %>
          <%= raw get_html_nested_comments(@topic.number, @comments) %>
      <% end %>
    </li>
  </ul>
</div>

<% if @comments %>
    <div class="row-fluid">
      <%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
    </div>
<% end %>